# Generated by Django 5.0.1 on 2024-02-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='Notes.note'),
        ),
    ]
