# Generated by Django 5.0.1 on 2024-02-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_user_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='reffering_user',
        ),
    ]
