# Generated by Django 5.0.1 on 2024-02-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_rename_user_note_reffering_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
    ]
