# Generated by Django 5.0.1 on 2024-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_author_tag_post_excerpt_alter_post_slug_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
