# Generated by Django 5.0.1 on 2024-02-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Talha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='Blog.author'),
        ),
    ]
